### ISSUE TITLE
DXF returns error

### ISSUE THREAD

**Issue by RecursiveVoid** [dotoritos-kim/dxf-json#13]
Hi! I tried to convert couple of DXF files where i get this error: 

"TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'Object'\n    |     property 'entries' -> object with constructor 'Object'\n    |     property 'ACAD_COLOR' -> object with constructor 'Object'\n    --- property 'ownerDictionarySoft' closes the circle"
}

and bunch of consol logs about Unsupported Entity: 
Unsupported ENTITY type: SEQEND

The DXF i was testing was directly exported from AUTOCAD as +2018 format. 

Any tips or solutions how to over come this problem?

**Comment by dotoritos-kim** [comment]
1. First of all, SEQEND is not currently supported.
2. #8 might be a hint here.

**Comment by RecursiveVoid** [comment]
thanks for the quick answer btw, 

I just noticed that i also get this log: parseTable: Invalid table name 'APPID' 

I will check your suggestion now. Thanks a lot

**Comment by dotoritos-kim** [comment]
[AppID](https://documentation.help/AutoCAD-DXF/WS1a9193826455f5ff18cb41610ec0a2e719-7a57.htm)
Currently, there is no function to parse APPID as a separate target.

**Comment by RecursiveVoid** [comment]
ALso, I tried with Dxf-Parser (the other npm package), it works fine with parsing the file. But they don't support hatches sadly xD.

**Comment by RecursiveVoid** [comment]
Thank you @dotoritos-kim with the suggestion. it worked pretty well. Here is the code adapted from your test. 

`    const parser = new DxfParser();
    const parsedDxf = parser.parseSync(dxfBuffer.toString('utf-8'))
    return JSON.parse(this._stringify(parsedDxf));
  

  private _stringify(obj: any): string {
    let cache: any = [];
    const str = JSON.stringify(obj, function (key, value) {
        if (typeof value === "object" && value !== null) {
            if (cache.indexOf(value) !== -1) {
                // Circular reference found, discard key
                return;
            }
            // Store value in our collection
            cache.push(value);
        }
        return value;
    });
    cache = null; // reset the cache
    return str;
  }
}`

**Comment by RecursiveVoid** [comment]
I will close the issue since it was super straight forward to fix it.  Thanks once again for the super speed support from your side btw!

**Comment by RecursiveVoid** [comment]
as a tip for the ones who experience this issue with the  circular references. ;  i found this package:  https://www.npmjs.com/package/json-stringify-safe
