### ISSUE TITLE
Issue with filterDummyBlocks Function: Removes All Entities in Paper Space Except the Last One

### ISSUE THREAD

**Issue by Hulideg** [dotoritos-kim/dxf-json#26]
Hello,

I am using your library for parsing DXF files and encountered an issue when applying the filterDummyBlocks function. As a result of the filtering, all entities in paper space are removed from the output JSON except for the last one. This leads to data loss and incorrect representation of the DXF file contents.

Thank you for your work

**Comment by dotoritos-kim** [comment]
Could you please send me the example file?

**Comment by Hulideg** [comment]
Your prompt response is truly inspiring!
I’ve created a minimal example file, Example.dxf, that clearly demonstrates the overzealous behavior of filterDummyBlocks.

In the log, you can distinctly observe the processing of all entities from each layout space. In this example:

Parsed entity: {
  handle: '31D',
  ownerBlockRecordSoftId: 'D2',
  isInPaperSpace: true,
  layer: '0',
  subclassMarker: 'AcDbMText',
  insertionPoint: { x: 15.65695043179357, y: 196.7505005533581, z: 0 },
  height: 2.5,
  width: 209.5356431211797,
  annotationHeight: 0,
  attachmentPoint: 1,
  drawingDirection: 5,
  text: 'Content from Layout1',
  lineSpacingStyle: 1,
  lineSpacing: 1
}
Parsed entity: {
  handle: '33A',
  ownerBlockRecordSoftId: 'D6',
  isInPaperSpace: true,
  layer: '0',
  subclassMarker: 'AcDbMText',
  insertionPoint: { x: 7.144712310906015, y: 261.0021254063658, z: 0 },
  height: 2.5,
  width: 209.5356431211797,
  annotationHeight: 0,
  attachmentPoint: 1,
  drawingDirection: 5,
  text: 'Content from Layout2',
  lineSpacingStyle: 1,
  lineSpacing: 1
}

However, the final file only retains one value – this happens with all files.
filterDummyBlocks removes all layouts except the one that was edited last before saving.

I also conducted a test with filterDummyBlocks disabled, which I’ve attached as well. When it’s disabled, data from all layouts is preserved, which indicates excessive filtering when the option is enabled.

Thank you for your assistance in resolving this!
[Dxf-json_.zip](https://github.com/user-attachments/files/18037800/Dxf-json_.zip)

**Comment by dotoritos-kim** [comment]
I have personally added the filterDummyBlocks feature for my own use. However, since you mentioned that it might be inconvenient, I will consider removing it in a future update.
It doesn't seem to be a bug in particular.
